Delmar/force-app/main/default/objects/DEL_CaseComment__c/DEL_CaseComment__c.object-meta.xml
<CustomObject>
    <label>Case Comment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_CaseComment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>DEL- This field is used to store the body of the comment</description>
    <label>Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_CaseComment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Comments</relationshipLabel>
    <relationshipName>CaseComments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Delmar/force-app/main/default/classes/DEL_EmailMessagesTriggerHandler.cls
public with sharing class DEL_EmailMessagesTriggerHandler {
    //handleEmailsOnInsert- 
    public static void handleEmailsOnInsert(List<EmailMessage> list_EmailMessages){
        String strPattern = '(<br>){1}';
        Pattern pattern = Pattern.compile(strPattern);
        List<DEL_CaseComment__c> list_CaseComments = new List<DEL_CaseComment__c>();
        for (EmailMessage objEmailMessage : list_EmailMessages) {
            if ((objEmailMessage.ThreadIdentifier <> objEmailMessage.MessageIdentifier) &&  objEmailMessage.Incoming == true){
                if (objEmailMessage.ParentId <> null){
                    DEL_CaseComment__c objCaseComment = new DEL_CaseComment__c();
                    objCaseComment.Case__c = objEmailMessage.ParentId;
                    if (String.isNotBlank(objEmailMessage.HtmlBody)){
                        String[] list_SplitResults = pattern.split(objEmailMessage.HtmlBody);
                        objCaseComment.Body__c = list_SplitResults.get(0).stripHtmlTags();
                    }
                    list_CaseComments.add(objCaseComment);
                }
            }
        }
        insert list_CaseComments;
    }
}