Delmar/force-app/main/default/objects/DEL_CaseComment__c/DEL_CaseComment__c.object-meta.xml
<CustomObject>
    <label>Case Comment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_CaseComment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>DEL- This field is used to store the body of the comment</description>
    <label>Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_CaseComment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Comments</relationshipLabel>
    <relationshipName>CaseComments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Delmar/force-app/main/default/classes/DEL_EmailMessagesTriggerHandlerTest.cls
/*******************************************************************************************************
* 
* @ Name            :   DEL_EmailMessagesTriggerHandlerTest
* @ Purpose         :   Test class for DEL_EmailMessagesTriggerHandler
* @ Author          :   Rakesh Nayak
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   19-07-2022      |  rakesh.nayak@absyz.com       |  1.0          |  Initial Version
*
*******************************************************************************************************/
@IsTest
private with sharing class DEL_EmailMessagesTriggerHandlerTest {
    /**
    * @ author      : Rakesh Nayak
    * @ description : This method is used to setup data for testing apex class 'DEL_EmailMessagesTriggerHandler'
    **/
    @TestSetup
    static void createData() {
        Case objCase = new Case(
            Status = 'New',
            Origin = 'Email',
            Subject = 'Test Case'
        );
        insert objCase;

        EmailMessage objEmailMessage = new EmailMessage(
            TextBody = 'This is textbody',
            HtmlBody = '<div>this is HtmlBody</div><br><body>Test</body>',
            Incoming = true,
            ThreadIdentifier = 'qwerty',
            MessageIdentifier = '1cwicjn',
            ParentId = objCase.Id
        );
        insert objEmailMessage;
    }

    /**
    * @ author      : Rakesh Nayak
    * @ description : This method is used to test the 'handleEmailsOnInsert' method on DEL_EmailMessagesTriggerHandler
    **/
    @IsTest
    private static void emailMessageTriggerTestMethod() {
        Case objCase = [SELECT Id FROM Case LIMIT 1];
        EmailMessage[] list_EmailMessages = [SELECT TextBody,
            HtmlBody,
            Incoming,
            ThreadIdentifier,
            MessageIdentifier,
            ParentId
            FROM EmailMessage
            WHERE ParentId = :objCase.Id];

        Test.startTest();
        DEL_EmailMessagesTriggerHandler.handleEmailsOnInsert(list_EmailMessages);
        Test.stopTest();

        DEL_CaseComment__c objCaseComment = [SELECT Id,
            Body__c,
            Case__c
            FROM DEL_CaseComment__c
            LIMIT 1];
        System.assertEquals(objCaseComment.Body__c, 'this is HtmlBody');
    }
}