Delmar/force-app/main/default/objects/DEL_CaseComment__c/DEL_CaseComment__c.object-meta.xml
<CustomObject>
    <label>Case Comment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_CaseComment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>DEL- This field is used to store the body of the comment</description>
    <label>Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_CaseComment__c/fields/CommentCreatedName__c.field-meta.xml
<CustomField>
    <fullName>CommentCreatedName__c</fullName>
    <label>Comment Created By Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_EmailAlertConfiguration__c/DEL_EmailAlertConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to manage the Merge Fields and Email Template used for email notification when Case Comments are created.</description>
    <label>Email Alert Configuration</label>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/DEL_ExceptionLog__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Name of the class in which exception has occurred.</description>
    <inlineHelpText>Name of the class in which exception has occurred.</inlineHelpText>
    <label>Class Name</label>
    <type>TextArea</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <description>Name of the method in which exception has occurred.</description>
    <inlineHelpText>Name of the method in which exception has occurred.</inlineHelpText>
    <label>Method Name</label>
    <type>TextArea</type>
</CustomField>

Delmar/force-app/main/default/classes/DEL_ContentDocumentLinkTriggerTest.cls
/*******************************************************************************************************
* 
* @ Name            :   DEL_ContentDocumentLinkTriggerTest
* @ Purpose         :   Test class for ContentDocumentLinkTriggerHelper
* @ Author          :   Rakesh Nayak
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   04-08-2022      |  rakesh.nayak@absyz.com       |  1.0          |  Initial Version
*
*******************************************************************************************************/
@isTest
public class DEL_ContentDocumentLinkTriggerTest {
    public static Boolean blnThrowException = false;

    /**
    * @ author       :  Rakesh Nayak
    * @ description  :  This method is used to setup data for testing apex class 'DEL_ContentDocumentLinkTriggerHelper'
    **/
    @TestSetup
    static void createTestData() {
        Case objCase = new DEL_TestUtility.CaseBuilder()
            .setSubject('Case with Power Failure')
            .setDescription('Power failure happens after 4 hour work')
            .setStatus('New')
            .setOrigin('Email')
            .createCase();
        insert objCase;
        
        OrgWideEmailAddress objOrgWideAddress = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress LIMIT 1];
        String strMergeFields = '{!Case.Subject},{!Case.CaseNumber},{!Case.Description},'
            +  '{!CaseComment.CommentCreatedName__c},{!CaseComment.Body__c},'
            + '{!CaseComment.CreatedDate},SiteLink';
        DEL_EmailAlertConfiguration__c objEmailAlertConfiguration = new DEL_TestUtility.EmailAlertConfigurationBuilder()
            .setMergeFields(strMergeFields)
            .setCaseQueryFields('Subject,CaseNumber,Description')
            .setCaseCommentFields('CommentCreatedName__c,Body__c,CreatedDate')
            .setSiteName('CaseComments')
            .setEmailTemplateName('DEL_CaseCommentAlert')
            .setOwnerId(UserInfo.getOrganizationId())
            .setOrgWideAddress(objOrgWideAddress.Address)
            .setEmailBreakPattern('(<br><div class="gmail_quote">){1}')
            .createConfiguration();
        insert objEmailAlertConfiguration;
        
        EmailTemplate objEmailTemplate = new DEL_TestUtility.EmailTemplateBuilder()
            .setName('Case Comment Email Alert')
            .setDeveloperName('DEL_CaseCommentAlert')
            .setHtmlValue('{!Case.Subject} SiteLink {!CaseComment.CommentCreatedName__c} {!CaseComment.CreatedDate}')
            .setFolderId(UserInfo.getOrganizationId())
            .setTemlateType('Custom')
            .createEmailTemplate();
        
        User objUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(objUser) {
            insert objEmailTemplate;
        }
        
        EmailMessage objEmailMessage = new DEL_TestUtility.EmailMessageBuilder()
            .setTextBody('This is textbody')
            .setHtmlBody('<div>this is HtmlBody</div><br><body>Test</body>')
            .setIncoming(true)
            .setFromAddress('abc@xyz.com')
            .setFromName('Test User')
            .setThreadIdentifier('qwerty')
            .setMessageIdentifier('1cwicjn')
            .setParentId(objCase.Id)
            .createEmailMessage();
        insert objEmailMessage;
        
        ContentVersion objContentVersion = new DEL_TestUtility.ContentVersionBuilder()
            .setTitle('Test')
            .setPathOnClient('image.jpg')
            .setVersionData('this is test data')
            .setIsMajorVersion(true)
            .createContentVersion();
        insert objContentVersion;
        
        ContentDocument objContentDocument = [SELECT 
                                              Id,
                                              Title,
                                              LatestPublishedVersionId
                                              FROM ContentDocument];
        
        ContentDocumentLink objContentDocumentLink = new DEL_TestUtility.ContentDocumentLinkBuilder()
            .setContentDocumentId(objContentDocument.Id)
            .setVisibility('AllUsers')
            .setShareType('V')
            .setLinkedEntityId(objEmailMessage.Id)
            .createContentDocumentLink();
        insert objContentDocumentLink;
    }

    /**
    * @ author       :  Rakesh Nayak
    * @ description  :  This method is used to test the method 'handleContentDocumentLinksOnInsert' in apex class 'DEL_ContentDocumentLinkTriggerHelper'
    **/
    @isTest
    private static void testContentDocumentLinkCreation() {
        ContentDocument objContentDocument = [SELECT 
                                              Id,
                                              Title,
                                              LatestPublishedVersionId
                                              FROM ContentDocument];
        
        List<ContentDocumentLink> list_ContentDocumentLinks = [SELECT 
                                                               Id,
                                                               Visibility,
                                                               ShareType,
                                                               LinkedEntityId,
                                                               ContentDocumentId
                                                               FROM ContentDocumentLink
                                                               WHERE ContentDocumentId = :objContentDocument.Id];
        
        Test.startTest();
        DEL_ContentDocumentLinkTriggerHelper.handleContentDocumentLinksOnInsert(list_ContentDocumentLinks);
        Test.stopTest();
        
        DEL_CaseComment__c objCasecomment = [SELECT Id FROM DEL_CaseComment__c];
        ContentDocumentLink objContentDocumentLink = [SELECT 
                                                      Id,
                                                      ShareType,
                                                      Visibility,
                                                      ContentDocumentId,
                                                      LinkedEntityId
                                                      FROM ContentDocumentLink
                                                      WHERE LinkedEntityId = :objCasecomment.Id];
        
        System.assertEquals(objCaseComment.Id, objContentDocumentLink.LinkedEntityId);
    }

    @isTest
    private static void handleExceptions() {
        ContentDocument objContentDocument = [SELECT 
                                              Id,
                                              Title,
                                              LatestPublishedVersionId
                                              FROM ContentDocument];
        
        List<ContentDocumentLink> list_ContentDocumentLinks = [SELECT 
                                                               Id,
                                                               Visibility,
                                                               ShareType,
                                                               LinkedEntityId,
                                                               ContentDocumentId
                                                               FROM ContentDocumentLink
                                                               WHERE ContentDocumentId = :objContentDocument.Id];
        
        Test.startTest();
        blnThrowException = true;
        DEL_ContentDocumentLinkTriggerHelper.handleContentDocumentLinksOnInsert(list_ContentDocumentLinks);
        Test.stopTest();
        
        List<DEL_ExceptionLog__c> list_ExceptionLogs = [SELECT 
                                                        Id, 
                                                        ClassName__c, 
                                                        MethodName__c
                                                        FROM DEL_ExceptionLog__c
                                                        WHERE MethodName__c = 'handleContentDocumentLinksOnInsert'];
        System.assert(!list_ExceptionLogs.isEmpty());
    }
}