Delmar/force-app/main/default/objects/DEL_CaseComment__c/DEL_CaseComment__c.object-meta.xml
<CustomObject>
    <label>Case Comment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_CaseComment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>DEL- This field is used to store the body of the comment</description>
    <label>Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_CaseComment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Comments</relationshipLabel>
    <relationshipName>CaseComments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Delmar/force-app/main/default/classes/DEL_CommentsPageControllerTest.cls
/*******************************************************************************************************
* 
* @ Name            :   DEL_CommentsPageControllerTest
* @ Purpose         :   Test class for DEL_CommentsPageController
* @ Author          :   Rakesh Nayak
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   27-06-2022      |  rakesh.nayak@absyz.com       |  1.0          |  Initial Version
*
*******************************************************************************************************/
@Istest
private class DEL_CommentsPageControllerTest {
    @TestSetup
    /**
    * @ author      : Rakesh Nayak
    * @ description : This method is used to setup data for testing apex class 'DEL_CommentsPageController'
    **/
    static void createData(){
        Case objCase = new Case(
            Status = 'New',
            Origin = 'Web'
        );
        insert objCase;
        String strCommentBody = 'Hey, Can I know the update';
        DEL_CaseComment__c objCaseComment = new DEL_CaseComment__c(
            Case__c = objCase.Id,
            Body__c = strCommentBody
        );
        insert objCaseComment;
    }

    /**
    * @ author      : Rakesh Nayak
    * @ description : This method is used to test the methods 'insertComment' and 'fetchComments' in apex class 'DEL_CommentsPageController'
    **/
    @IsTest
    private static void caseCommentTestMethod() {
        String strCommentBody = 'Hi Sir';
        Test.startTest();
        Case objCase = [SELECT Id FROM Case LIMIT 1];
        Id idCaseCommentId = DEL_CommentsPageController.insertComment(strCommentBody, objCase.Id);
        List<DEL_CaseComment__c> list_comments = DEL_CommentsPageController.fetchComments(objCase.Id);
        Test.stopTest();
        System.assertEquals(2, list_comments.size());
    }  
}