Delmar/force-app/main/default/objects/DEL_CaseCollaborator__c/DEL_CaseCollaborator__c.object-meta.xml
<CustomObject>
    <label>Case Collaborator</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Case Collaborator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Collaborators</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_CaseCollaborator__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Collaborators</relationshipLabel>
    <relationshipName>Case_Collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_CaseCollaborator__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

Delmar/force-app/main/default/classes/DEL_ContactCollaborationTwoController.cls
public without sharing class DEL_ContactCollaborationTwoController {
    public class ResponseWrapper {
        @AuraEnabled public Boolean blnIsSuccess;
        @AuraEnabled public String strErrorMessage;
        @AuraEnabled public List<User> list_Users;
        
        public ResponseWrapper() {
            this.blnIsSuccess = true;
            this.strErrorMessage = '';
            this.list_Users = new List<User>();
        }
    }

    public static List<User> getUser(Id idCaseId, String strUserName, Id currentId) {
        List<User> list_User = new List<User>();
       try {
        Case objCase = [SELECT 
                            Id,
                            AccountId,
                            ContactId 
                            FROM Case
                            WHERE Id = :idCaseId];
            String strPattern = '%' + strUserName + '%';
             list_User = [SELECT 
                                             AccountId, 
                                             ContactId, 
                                             Id, 
                                             Name, 
                                             Username, 
                                             Email 
                                             FROM User 
                                             WHERE Name LIKE :strpattern AND Id <>: currentId
                                             AND AccountId = :objCase.AccountId];
       } catch (Exception obj_exception) {
         system.debug(obj_exception.getMessage());
       }
      return list_User;
    }

    public static List<DEL_CaseCollaborator__c> addUser(List<Id> list_UserIds, Id idCaseId) {

        List<DEL_CaseCollaborator__c> list_objCaseCollaborators = new List<DEL_CaseCollaborator__c>();
        
        try {
            for (Id idUser : list_UserIds) {
                DEL_CaseCollaborator__c objCaseCollaborator = new DEL_CaseCollaborator__c (
                    User__c = idUser,
                    Case__c = idCaseId
                );
                list_objCaseCollaborators.add(objCaseCollaborator);
            }
            
            if (!list_objCaseCollaborators.isEmpty()) {
                insert list_objCaseCollaborators;
            }
            
        } catch(Exception obj_Exception) {
            system.debug(obj_exception.getMessage());
        }
     return list_objCaseCollaborators;
}
}