Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/DEL_ExceptionLog__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Name of the class in which exception has occurred.</description>
    <inlineHelpText>Name of the class in which exception has occurred.</inlineHelpText>
    <label>Class Name</label>
    <type>TextArea</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Specifies the type of exception that has occurred.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <description>Name of the method in which exception has occurred.</description>
    <inlineHelpText>Name of the method in which exception has occurred.</inlineHelpText>
    <label>Method Name</label>
    <type>TextArea</type>
</CustomField>

Delmar/force-app/main/default/classes/DEL_Utils.cls
/*******************************************************************************************************
* 
* @ Name            :   DEL_Utils
* @ Purpose         :   Common functionalities can be created as methods in this class 
                        and used across various classes
* @ Author          :   Ankit C
* @ Test Class Name :   DEL_UtilsTest
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*  26-07-2022       |  ankit.c@absyz.com            |  1.0          |  Initial version
*******************************************************************************************************/
public class DEL_Utils {
    /**
    * @ author      : Ankit C
    * @ description : This method is used to initialize/insert a DEL_ExceptionLog__c record
                      based on the input parameters.
    * @ params      : strClassName - Class name where exception has occurred
                      strMethodName - Method name where exception has occurred
                      objException - Exception object
                      blnIsInsertMode - if set as true, then the record will be inserted else it won't
    * @ return      : DEL_ExceptionLog__c - new record which is inserted/initialized.
    **/
    public static DEL_ExceptionLog__c logException(
        String strClassName, 
        String strMethodName, 
        Exception objException, 
        Boolean blnIsInsertMode
    ) {
        DEL_ExceptionLog__c objExceptionLog = new DEL_ExceptionLog__c(
            ClassName__c = strClassName,
            MethodName__c = strMethodName,
            ErrorMessage__c = objException.getMessage(),
            StackTrace__c = objException.getStackTraceString(),
            ExceptionType__c = objException.getTypeName()
        );

        if (blnIsInsertMode) {
            insert objExceptionLog;
        }

        return objExceptionLog;
    }
}