Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/DEL_ExceptionLog__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Delmar/force-app/main/default/objects/DEL_ExceptionLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Specifies the type of exception that has occurred.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Delmar/force-app/main/default/classes/DEL_UtilsTest.cls
/*******************************************************************************************************
* 
* @ Name            :   DEL_UtilsTest
* @ Purpose         :   Test class for the DEL_Utils class.
* @ Author          :   Ankit C
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*  26-07-2022       |  ankit.c@absyz.com            |  1.0          |  Initial version
*******************************************************************************************************/
@IsTest
private class DEL_UtilsTest {
    /**
     * @ author      : Ankit C
     * @ description : Test method for logException() method in DEL_Utils class
    **/
    @IsTest
    private static void testLogException() {
        Account objAccount = new Account();
        DEL_ExceptionLog__c objExceptionLog = new DEL_ExceptionLog__c();
        Test.startTest();
        try {
            // This DML will fail as Name is required.
            insert objAccount;
        } catch (Exception objException) {
            objExceptionLog = DEL_Utils.logException(
                'DEL_UtilsTest',
                'testLogException',
                objException,
                true
            );
        }
        Test.stopTest();

        // Assert if an DEL_ExceptionLog__c record was created of DML Type
        System.assert(objExceptionLog.Id != null);
        System.assertEquals('System.DmlException', objExceptionLog.ExceptionType__c, 'Record was not created.');
    }
}